unique_ids:
  forms:
    Form1: OW73547WVJHUNLQIGGIGZYKL7NJFRDAM
    Form1.ItemTemplate1: '1713987745008693481271213.1268'
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: ZWT53DHOZP4JC4V3S36K4X4XGSPUEAAA
    theme.css: WJO2NOFBP6FYP3RFH5U7UNYXTHZQFUQF
  scripts: {}
